version: '3.3'
volumes:
  data:
services:
  selenium:
    restart: always
    image: selenium/standalone-chrome-debug
    ports:
      - "4444:4444"
      - "59000:59000"
    container_name: selenium
  ruby:
    image: ruby
    links:
      - "selenium:selenium"
    command: bundle install
    command: bundle exec cucumber -p ci
